apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  strategy:  # Change the deployment strategy to "Recreate"
    type: Recreate  # Use "Recreate" to delete existing pods and create new ones
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: rohanmaharjan100/test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
