apiVersion: v1
kind: Service
metadata:
   #the Serivce Name- it should match with the lable name of the deployment 
  name: test
spec:
  #type of the service
  type: NodePort
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 31001