name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: do-something

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i harness-lighthouse
    - run: npx harness-lighthouse --url https://www.facebook.com
    - run: ls
    - uses: actions/checkout@v1
    - run: mkdir -p output/
    - run: echo "This is fancy a comment" > output/results.txt
    - uses: actions/upload-artifact@v1
      with:
          name: results
          path: output
    - uses: actions/download-artifact@v1
      with:
          name: results
    - name: comment PR
      uses: machine-learning-apps/pr-comment@master
      env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
          path: results/result.txt
