name: Lighthouse
on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'The environment to deploy to'
          required: false
          default: 'production'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i harness-lighthouse
    - run: npx harness-lighthouse --url https://www.facebook.com/
    - run: ls
    - uses: actions/upload-artifact@v1
      with:
          name: result
          path: output

    - uses: actions/download-artifact@v1
      with:
          name: result
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
          message: |
                        Thank you for your contribution. We aim to review it within 48 hours!
          comment_includes: "Thank you"
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
             
             
             

          
